name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install (Chezmoi)
        run: apt install chezmoi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply
        run: chezmoi apply .

  macOS:
    runs-on: macos-latest

    steps:
      - name: Install (Chezmoi)
        run: brew install chezmoi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply
        run: chezmoi apply .
